### ISSUE TITLE
feat: Validate degree plan information

### ISSUE THREAD

**Issue by medhaaiyah** [acmutd/nebula-web#5]
## Problem Description

This segment is in charge of making sure if a particular class meets certain _pre-reqs_ and _co-req_. If it doesn't then it will display a warning message. It will also determine that a particular student is not exceeding taking 18 _credit hours per semester_.

## Task List

 - [ ] Determine the components required for each of the functions (aspects are itlized)
 - [ ] Pseudocode each of the functions
 - [ ] Write the appropriate code accordingly

**Comment by WillieCubed** [comment]
Closing due to being stale
